# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Cancel
version:      1.02
version_from: lib/Thread/Cancel.pm
installdirs:  site
requires:
    Test::More:                    0.5
    threads:                       1.36

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
